services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    volumes:
      # path esterno: path sul container
      - ./src/db.sqlite3:/src/db.sqlite3     # Volume per il database
      - ./media:/src/media                   # Volume per i media files
    environment:
      - PEGASO_MEDIA_URL=/media/
      - PEGASO_MEDIA_ROOT=/src/media/
      - DJANGO_SETTINGS_MODULE=albdif.config.settings
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
volumes:
  dbdata:
    driver: local
