# Generated by Django 4.2.17 on 2024-12-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albdif', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='costo_soggiorno',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagione',
            name='prezzo_default',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=7),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='stato_prenotazione',
            field=models.CharField(choices=[('PR', 'Prenotata'), ('PG', 'Pagata'), ('CA', 'Cancellata')], default='PR', max_length=2),
        ),
    ]
