# Generated by Django 4.2.17 on 2024-12-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albdif', '0002_prenotazione_costo_soggiorno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='numero_posti_letto',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='numero_persone',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
