# Generated by Django 4.2.17 on 2025-01-02 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('albdif', '0005_alter_host_utente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servizio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione_servizio', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Servizio',
                'verbose_name_plural': 'Servizi',
            },
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': 'Host', 'verbose_name_plural': 'Hosts'},
        ),
        migrations.RemoveField(
            model_name='camera',
            name='services',
        ),
        migrations.AlterField(
            model_name='calendarioprenotazione',
            name='data_fine',
            field=models.DateField(help_text='Data fine soggiorno'),
        ),
        migrations.AlterField(
            model_name='calendarioprenotazione',
            name='data_inizio',
            field=models.DateField(help_text='Data inizio soggiorno'),
        ),
        migrations.AlterField(
            model_name='host',
            name='utente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visitatore',
            name='utente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ServizioCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incluso', models.BooleanField(default=False)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albdif.camera')),
                ('servizio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albdif.servizio')),
            ],
            options={
                'verbose_name': 'Servizio camera',
                'verbose_name_plural': 'Servizi camera',
            },
        ),
    ]
