# Generated by Django 4.2.17 on 2025-01-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albdif', '0006_servizio_alter_host_options_remove_camera_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprieta',
            name='descrizione',
            field=models.CharField(max_length=2000),
        ),
    ]
