# Generated by Django 4.2.17 on 2025-01-03 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albdif', '0007_alter_proprieta_descrizione'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='version',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 13, 26, 19, 54955)),
        ),
    ]
